### PR TITLE
Fix spinning wheel in boot apps view

### LINKED ISSUE #216: Spring boot Dashboard keep spinning
image

### PR DESCRIPTION
**Pull request by BoykoAlex**
Try to match custom debug event against project name in `BootApp` and `DebugSession`.
The fix in memory provider is just to avoid errors in the console

Fixes #216

### CODE REVIEW

File: src/views/memory.ts [hunk 1]
```diff
@@ -153,7 +153,7 @@ export class MemoryViewProvider implements vscode.WebviewViewProvider {
                 case "FetchData": {
                     const type = message.type;
                     if (processKey === '') {
-                        processKey = this.storeLiveProcesses.values().next().value.liveProcess.processKey;
+                        processKey = this.storeLiveProcesses.values().next().value.liveProcess?.processKey;
                     }
                     if (type !== '' && type === "Heap Memory" && processKey !== undefined && processKey !== '') {
```
Comment (Eskibear) [inline src/views/memory.ts:158]: > type !== '' && type === "Heap Memory"

`type !== ''` is obviously unnecessary. A lot of chaos in conditional checks, we might fix that in a separate PR, gracefully checking whether type of processkey is null or empty. @testforstephen

**Review by Eskibear — APPROVED** [review]
LGTM. Thanks Alex!

@testforstephen please help to verify.

**Comment by BoykoAlex** [comment]
Likely custom debug event with PID and debug session started event were coming in reverse order previosly, i.e. debug session started first and then custome debug event with PID...

**Review by testforstephen — APPROVED** [review]
LGTM. The test failure is unrelated to this change, we can use a separate PR to fix the test.

**Comment by testforstephen** [comment]
@BoykoAlex thanks for the fix.
